// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: announcement/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the announcement module's genesis state.
type GenesisState struct {
	PortId                   string                `protobuf:"bytes,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	BroadcastList            []Broadcast           `protobuf:"bytes,2,rep,name=broadcastList,proto3" json:"broadcastList"`
	BroadcastCount           uint64                `protobuf:"varint,3,opt,name=broadcastCount,proto3" json:"broadcastCount,omitempty"`
	SentAnnouncementList     []SentAnnouncement    `protobuf:"bytes,4,rep,name=sentAnnouncementList,proto3" json:"sentAnnouncementList"`
	SentAnnouncementCount    uint64                `protobuf:"varint,5,opt,name=sentAnnouncementCount,proto3" json:"sentAnnouncementCount,omitempty"`
	TimeoutAnnouncementList  []TimeoutAnnouncement `protobuf:"bytes,6,rep,name=timeoutAnnouncementList,proto3" json:"timeoutAnnouncementList"`
	TimeoutAnnouncementCount uint64                `protobuf:"varint,7,opt,name=timeoutAnnouncementCount,proto3" json:"timeoutAnnouncementCount,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_877ad115eab7c7b4, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetPortId() string {
	if m != nil {
		return m.PortId
	}
	return ""
}

func (m *GenesisState) GetBroadcastList() []Broadcast {
	if m != nil {
		return m.BroadcastList
	}
	return nil
}

func (m *GenesisState) GetBroadcastCount() uint64 {
	if m != nil {
		return m.BroadcastCount
	}
	return 0
}

func (m *GenesisState) GetSentAnnouncementList() []SentAnnouncement {
	if m != nil {
		return m.SentAnnouncementList
	}
	return nil
}

func (m *GenesisState) GetSentAnnouncementCount() uint64 {
	if m != nil {
		return m.SentAnnouncementCount
	}
	return 0
}

func (m *GenesisState) GetTimeoutAnnouncementList() []TimeoutAnnouncement {
	if m != nil {
		return m.TimeoutAnnouncementList
	}
	return nil
}

func (m *GenesisState) GetTimeoutAnnouncementCount() uint64 {
	if m != nil {
		return m.TimeoutAnnouncementCount
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "Liberty30.usappchain.announcement.GenesisState")
}

func init() { proto.RegisterFile("announcement/genesis.proto", fileDescriptor_877ad115eab7c7b4) }

var fileDescriptor_877ad115eab7c7b4 = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x3f, 0x4f, 0xc2, 0x40,
	0x18, 0xc6, 0x5b, 0xa9, 0x10, 0xcf, 0x3f, 0xc3, 0x05, 0x43, 0x43, 0x4c, 0x45, 0x63, 0x94, 0x41,
	0x5a, 0x23, 0x86, 0xc1, 0x4d, 0x1c, 0x8c, 0x09, 0x83, 0x01, 0x07, 0xe3, 0x42, 0xae, 0xe5, 0x52,
	0x6e, 0xe8, 0xdd, 0xa5, 0x77, 0x35, 0xb2, 0xfa, 0x09, 0xfc, 0x58, 0x8c, 0x8c, 0x4e, 0xc6, 0xc0,
	0x17, 0x31, 0x5c, 0x2b, 0xa1, 0xa5, 0x44, 0xb6, 0xb7, 0xcf, 0xf3, 0x3e, 0x4f, 0x7e, 0x6d, 0x5f,
	0x50, 0x45, 0x94, 0xb2, 0x88, 0x7a, 0x38, 0xc0, 0x54, 0x3a, 0x3e, 0xa6, 0x58, 0x10, 0x61, 0xf3,
	0x90, 0x49, 0x06, 0x4f, 0x3a, 0xc4, 0xc5, 0xa1, 0x1c, 0x35, 0xaf, 0xec, 0x48, 0x20, 0xce, 0xbd,
	0x21, 0x22, 0xd4, 0x5e, 0x0e, 0x54, 0x8f, 0x52, 0x71, 0x37, 0x64, 0x68, 0xe0, 0x21, 0x21, 0xe3,
	0x82, 0xea, 0x59, 0xca, 0x15, 0x98, 0xca, 0xfe, 0xb2, 0x92, 0x6c, 0x5d, 0xa4, 0xb6, 0x24, 0x09,
	0x30, 0x8b, 0x72, 0x17, 0xcb, 0x3e, 0xf3, 0x99, 0x1a, 0x9d, 0xf9, 0x14, 0xab, 0xa7, 0x1f, 0x06,
	0xd8, 0x7b, 0x88, 0xb9, 0x7b, 0x12, 0x49, 0x0c, 0x2b, 0xa0, 0xc4, 0x59, 0x28, 0xfb, 0x64, 0x60,
	0xea, 0x35, 0xbd, 0xbe, 0xd3, 0x2d, 0xce, 0x1f, 0x1f, 0x07, 0xf0, 0x05, 0xec, 0x2f, 0x08, 0x3b,
	0x44, 0x48, 0x73, 0xab, 0x56, 0xa8, 0xef, 0x5e, 0x5f, 0xda, 0xff, 0xbe, 0xa7, 0xdd, 0xfe, 0xcb,
	0xb5, 0x8d, 0xf1, 0xf7, 0xb1, 0xd6, 0x4d, 0x17, 0xc1, 0x73, 0x70, 0xb0, 0x10, 0xee, 0x59, 0x44,
	0xa5, 0x59, 0xa8, 0xe9, 0x75, 0xa3, 0x9b, 0x51, 0x61, 0x00, 0xca, 0xf3, 0xaf, 0x70, 0xb7, 0x54,
	0xad, 0x40, 0x0c, 0x05, 0xd2, 0xdc, 0x00, 0xa4, 0x97, 0x89, 0x27, 0x3c, 0xb9, 0xb5, 0xf0, 0x06,
	0x1c, 0x66, 0xf5, 0x98, 0x6e, 0x5b, 0xd1, 0xe5, 0x9b, 0xf0, 0x0d, 0x54, 0x92, 0x9f, 0xb0, 0xc2,
	0x59, 0x54, 0x9c, 0xad, 0x0d, 0x38, 0x9f, 0x57, 0x1b, 0x12, 0xd4, 0x75, 0xe5, 0xf0, 0x16, 0x98,
	0x39, 0x56, 0x0c, 0x5c, 0x52, 0xc0, 0x6b, 0xfd, 0xf6, 0xd3, 0x78, 0x6a, 0xe9, 0x93, 0xa9, 0xa5,
	0xff, 0x4c, 0x2d, 0xfd, 0x73, 0x66, 0x69, 0x93, 0x99, 0xa5, 0x7d, 0xcd, 0x2c, 0xed, 0xb5, 0xe5,
	0x13, 0x39, 0x8c, 0x5c, 0xdb, 0x63, 0x81, 0xb3, 0xc0, 0x76, 0x22, 0xd1, 0x40, 0x9c, 0x37, 0x14,
	0xb8, 0xf3, 0xee, 0xa4, 0x2f, 0x70, 0xc4, 0xb1, 0x70, 0x8b, 0xea, 0xba, 0x9a, 0xbf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xce, 0x2e, 0xbc, 0x47, 0x21, 0x03, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TimeoutAnnouncementCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.TimeoutAnnouncementCount))
		i--
		dAtA[i] = 0x38
	}
	if len(m.TimeoutAnnouncementList) > 0 {
		for iNdEx := len(m.TimeoutAnnouncementList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TimeoutAnnouncementList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if m.SentAnnouncementCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.SentAnnouncementCount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.SentAnnouncementList) > 0 {
		for iNdEx := len(m.SentAnnouncementList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SentAnnouncementList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.BroadcastCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.BroadcastCount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.BroadcastList) > 0 {
		for iNdEx := len(m.BroadcastList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BroadcastList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.PortId) > 0 {
		i -= len(m.PortId)
		copy(dAtA[i:], m.PortId)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.PortId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PortId)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.BroadcastList) > 0 {
		for _, e := range m.BroadcastList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.BroadcastCount != 0 {
		n += 1 + sovGenesis(uint64(m.BroadcastCount))
	}
	if len(m.SentAnnouncementList) > 0 {
		for _, e := range m.SentAnnouncementList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.SentAnnouncementCount != 0 {
		n += 1 + sovGenesis(uint64(m.SentAnnouncementCount))
	}
	if len(m.TimeoutAnnouncementList) > 0 {
		for _, e := range m.TimeoutAnnouncementList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.TimeoutAnnouncementCount != 0 {
		n += 1 + sovGenesis(uint64(m.TimeoutAnnouncementCount))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PortId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PortId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BroadcastList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BroadcastList = append(m.BroadcastList, Broadcast{})
			if err := m.BroadcastList[len(m.BroadcastList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BroadcastCount", wireType)
			}
			m.BroadcastCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BroadcastCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SentAnnouncementList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SentAnnouncementList = append(m.SentAnnouncementList, SentAnnouncement{})
			if err := m.SentAnnouncementList[len(m.SentAnnouncementList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SentAnnouncementCount", wireType)
			}
			m.SentAnnouncementCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SentAnnouncementCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutAnnouncementList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TimeoutAnnouncementList = append(m.TimeoutAnnouncementList, TimeoutAnnouncement{})
			if err := m.TimeoutAnnouncementList[len(m.TimeoutAnnouncementList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutAnnouncementCount", wireType)
			}
			m.TimeoutAnnouncementCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeoutAnnouncementCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
