// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: announcement/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryGetBroadcastRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetBroadcastRequest) Reset()         { *m = QueryGetBroadcastRequest{} }
func (m *QueryGetBroadcastRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetBroadcastRequest) ProtoMessage()    {}
func (*QueryGetBroadcastRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1683cf4edaf7e74, []int{0}
}
func (m *QueryGetBroadcastRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetBroadcastRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetBroadcastRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetBroadcastRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetBroadcastRequest.Merge(m, src)
}
func (m *QueryGetBroadcastRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetBroadcastRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetBroadcastRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetBroadcastRequest proto.InternalMessageInfo

func (m *QueryGetBroadcastRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetBroadcastResponse struct {
	Broadcast Broadcast `protobuf:"bytes,1,opt,name=Broadcast,proto3" json:"Broadcast"`
}

func (m *QueryGetBroadcastResponse) Reset()         { *m = QueryGetBroadcastResponse{} }
func (m *QueryGetBroadcastResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetBroadcastResponse) ProtoMessage()    {}
func (*QueryGetBroadcastResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1683cf4edaf7e74, []int{1}
}
func (m *QueryGetBroadcastResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetBroadcastResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetBroadcastResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetBroadcastResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetBroadcastResponse.Merge(m, src)
}
func (m *QueryGetBroadcastResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetBroadcastResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetBroadcastResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetBroadcastResponse proto.InternalMessageInfo

func (m *QueryGetBroadcastResponse) GetBroadcast() Broadcast {
	if m != nil {
		return m.Broadcast
	}
	return Broadcast{}
}

type QueryAllBroadcastRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllBroadcastRequest) Reset()         { *m = QueryAllBroadcastRequest{} }
func (m *QueryAllBroadcastRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllBroadcastRequest) ProtoMessage()    {}
func (*QueryAllBroadcastRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1683cf4edaf7e74, []int{2}
}
func (m *QueryAllBroadcastRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllBroadcastRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllBroadcastRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllBroadcastRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllBroadcastRequest.Merge(m, src)
}
func (m *QueryAllBroadcastRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllBroadcastRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllBroadcastRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllBroadcastRequest proto.InternalMessageInfo

func (m *QueryAllBroadcastRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllBroadcastResponse struct {
	Broadcast  []Broadcast         `protobuf:"bytes,1,rep,name=Broadcast,proto3" json:"Broadcast"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllBroadcastResponse) Reset()         { *m = QueryAllBroadcastResponse{} }
func (m *QueryAllBroadcastResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllBroadcastResponse) ProtoMessage()    {}
func (*QueryAllBroadcastResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1683cf4edaf7e74, []int{3}
}
func (m *QueryAllBroadcastResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllBroadcastResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllBroadcastResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllBroadcastResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllBroadcastResponse.Merge(m, src)
}
func (m *QueryAllBroadcastResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllBroadcastResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllBroadcastResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllBroadcastResponse proto.InternalMessageInfo

func (m *QueryAllBroadcastResponse) GetBroadcast() []Broadcast {
	if m != nil {
		return m.Broadcast
	}
	return nil
}

func (m *QueryAllBroadcastResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetSentAnnouncementRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetSentAnnouncementRequest) Reset()         { *m = QueryGetSentAnnouncementRequest{} }
func (m *QueryGetSentAnnouncementRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetSentAnnouncementRequest) ProtoMessage()    {}
func (*QueryGetSentAnnouncementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1683cf4edaf7e74, []int{4}
}
func (m *QueryGetSentAnnouncementRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSentAnnouncementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSentAnnouncementRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSentAnnouncementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSentAnnouncementRequest.Merge(m, src)
}
func (m *QueryGetSentAnnouncementRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSentAnnouncementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSentAnnouncementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSentAnnouncementRequest proto.InternalMessageInfo

func (m *QueryGetSentAnnouncementRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetSentAnnouncementResponse struct {
	SentAnnouncement SentAnnouncement `protobuf:"bytes,1,opt,name=SentAnnouncement,proto3" json:"SentAnnouncement"`
}

func (m *QueryGetSentAnnouncementResponse) Reset()         { *m = QueryGetSentAnnouncementResponse{} }
func (m *QueryGetSentAnnouncementResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetSentAnnouncementResponse) ProtoMessage()    {}
func (*QueryGetSentAnnouncementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1683cf4edaf7e74, []int{5}
}
func (m *QueryGetSentAnnouncementResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSentAnnouncementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSentAnnouncementResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSentAnnouncementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSentAnnouncementResponse.Merge(m, src)
}
func (m *QueryGetSentAnnouncementResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSentAnnouncementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSentAnnouncementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSentAnnouncementResponse proto.InternalMessageInfo

func (m *QueryGetSentAnnouncementResponse) GetSentAnnouncement() SentAnnouncement {
	if m != nil {
		return m.SentAnnouncement
	}
	return SentAnnouncement{}
}

type QueryAllSentAnnouncementRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllSentAnnouncementRequest) Reset()         { *m = QueryAllSentAnnouncementRequest{} }
func (m *QueryAllSentAnnouncementRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllSentAnnouncementRequest) ProtoMessage()    {}
func (*QueryAllSentAnnouncementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1683cf4edaf7e74, []int{6}
}
func (m *QueryAllSentAnnouncementRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllSentAnnouncementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllSentAnnouncementRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllSentAnnouncementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllSentAnnouncementRequest.Merge(m, src)
}
func (m *QueryAllSentAnnouncementRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllSentAnnouncementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllSentAnnouncementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllSentAnnouncementRequest proto.InternalMessageInfo

func (m *QueryAllSentAnnouncementRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllSentAnnouncementResponse struct {
	SentAnnouncement []SentAnnouncement  `protobuf:"bytes,1,rep,name=SentAnnouncement,proto3" json:"SentAnnouncement"`
	Pagination       *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllSentAnnouncementResponse) Reset()         { *m = QueryAllSentAnnouncementResponse{} }
func (m *QueryAllSentAnnouncementResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllSentAnnouncementResponse) ProtoMessage()    {}
func (*QueryAllSentAnnouncementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1683cf4edaf7e74, []int{7}
}
func (m *QueryAllSentAnnouncementResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllSentAnnouncementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllSentAnnouncementResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllSentAnnouncementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllSentAnnouncementResponse.Merge(m, src)
}
func (m *QueryAllSentAnnouncementResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllSentAnnouncementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllSentAnnouncementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllSentAnnouncementResponse proto.InternalMessageInfo

func (m *QueryAllSentAnnouncementResponse) GetSentAnnouncement() []SentAnnouncement {
	if m != nil {
		return m.SentAnnouncement
	}
	return nil
}

func (m *QueryAllSentAnnouncementResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetTimeoutAnnouncementRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetTimeoutAnnouncementRequest) Reset()         { *m = QueryGetTimeoutAnnouncementRequest{} }
func (m *QueryGetTimeoutAnnouncementRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetTimeoutAnnouncementRequest) ProtoMessage()    {}
func (*QueryGetTimeoutAnnouncementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1683cf4edaf7e74, []int{8}
}
func (m *QueryGetTimeoutAnnouncementRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetTimeoutAnnouncementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetTimeoutAnnouncementRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetTimeoutAnnouncementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTimeoutAnnouncementRequest.Merge(m, src)
}
func (m *QueryGetTimeoutAnnouncementRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetTimeoutAnnouncementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTimeoutAnnouncementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTimeoutAnnouncementRequest proto.InternalMessageInfo

func (m *QueryGetTimeoutAnnouncementRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetTimeoutAnnouncementResponse struct {
	TimeoutAnnouncement TimeoutAnnouncement `protobuf:"bytes,1,opt,name=TimeoutAnnouncement,proto3" json:"TimeoutAnnouncement"`
}

func (m *QueryGetTimeoutAnnouncementResponse) Reset()         { *m = QueryGetTimeoutAnnouncementResponse{} }
func (m *QueryGetTimeoutAnnouncementResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetTimeoutAnnouncementResponse) ProtoMessage()    {}
func (*QueryGetTimeoutAnnouncementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1683cf4edaf7e74, []int{9}
}
func (m *QueryGetTimeoutAnnouncementResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetTimeoutAnnouncementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetTimeoutAnnouncementResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetTimeoutAnnouncementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTimeoutAnnouncementResponse.Merge(m, src)
}
func (m *QueryGetTimeoutAnnouncementResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetTimeoutAnnouncementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTimeoutAnnouncementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTimeoutAnnouncementResponse proto.InternalMessageInfo

func (m *QueryGetTimeoutAnnouncementResponse) GetTimeoutAnnouncement() TimeoutAnnouncement {
	if m != nil {
		return m.TimeoutAnnouncement
	}
	return TimeoutAnnouncement{}
}

type QueryAllTimeoutAnnouncementRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllTimeoutAnnouncementRequest) Reset()         { *m = QueryAllTimeoutAnnouncementRequest{} }
func (m *QueryAllTimeoutAnnouncementRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllTimeoutAnnouncementRequest) ProtoMessage()    {}
func (*QueryAllTimeoutAnnouncementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1683cf4edaf7e74, []int{10}
}
func (m *QueryAllTimeoutAnnouncementRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllTimeoutAnnouncementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllTimeoutAnnouncementRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllTimeoutAnnouncementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllTimeoutAnnouncementRequest.Merge(m, src)
}
func (m *QueryAllTimeoutAnnouncementRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllTimeoutAnnouncementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllTimeoutAnnouncementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllTimeoutAnnouncementRequest proto.InternalMessageInfo

func (m *QueryAllTimeoutAnnouncementRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllTimeoutAnnouncementResponse struct {
	TimeoutAnnouncement []TimeoutAnnouncement `protobuf:"bytes,1,rep,name=TimeoutAnnouncement,proto3" json:"TimeoutAnnouncement"`
	Pagination          *query.PageResponse   `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllTimeoutAnnouncementResponse) Reset()         { *m = QueryAllTimeoutAnnouncementResponse{} }
func (m *QueryAllTimeoutAnnouncementResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllTimeoutAnnouncementResponse) ProtoMessage()    {}
func (*QueryAllTimeoutAnnouncementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1683cf4edaf7e74, []int{11}
}
func (m *QueryAllTimeoutAnnouncementResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllTimeoutAnnouncementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllTimeoutAnnouncementResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllTimeoutAnnouncementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllTimeoutAnnouncementResponse.Merge(m, src)
}
func (m *QueryAllTimeoutAnnouncementResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllTimeoutAnnouncementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllTimeoutAnnouncementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllTimeoutAnnouncementResponse proto.InternalMessageInfo

func (m *QueryAllTimeoutAnnouncementResponse) GetTimeoutAnnouncement() []TimeoutAnnouncement {
	if m != nil {
		return m.TimeoutAnnouncement
	}
	return nil
}

func (m *QueryAllTimeoutAnnouncementResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetBroadcastRequest)(nil), "Liberty30.usappchain.announcement.QueryGetBroadcastRequest")
	proto.RegisterType((*QueryGetBroadcastResponse)(nil), "Liberty30.usappchain.announcement.QueryGetBroadcastResponse")
	proto.RegisterType((*QueryAllBroadcastRequest)(nil), "Liberty30.usappchain.announcement.QueryAllBroadcastRequest")
	proto.RegisterType((*QueryAllBroadcastResponse)(nil), "Liberty30.usappchain.announcement.QueryAllBroadcastResponse")
	proto.RegisterType((*QueryGetSentAnnouncementRequest)(nil), "Liberty30.usappchain.announcement.QueryGetSentAnnouncementRequest")
	proto.RegisterType((*QueryGetSentAnnouncementResponse)(nil), "Liberty30.usappchain.announcement.QueryGetSentAnnouncementResponse")
	proto.RegisterType((*QueryAllSentAnnouncementRequest)(nil), "Liberty30.usappchain.announcement.QueryAllSentAnnouncementRequest")
	proto.RegisterType((*QueryAllSentAnnouncementResponse)(nil), "Liberty30.usappchain.announcement.QueryAllSentAnnouncementResponse")
	proto.RegisterType((*QueryGetTimeoutAnnouncementRequest)(nil), "Liberty30.usappchain.announcement.QueryGetTimeoutAnnouncementRequest")
	proto.RegisterType((*QueryGetTimeoutAnnouncementResponse)(nil), "Liberty30.usappchain.announcement.QueryGetTimeoutAnnouncementResponse")
	proto.RegisterType((*QueryAllTimeoutAnnouncementRequest)(nil), "Liberty30.usappchain.announcement.QueryAllTimeoutAnnouncementRequest")
	proto.RegisterType((*QueryAllTimeoutAnnouncementResponse)(nil), "Liberty30.usappchain.announcement.QueryAllTimeoutAnnouncementResponse")
}

func init() { proto.RegisterFile("announcement/query.proto", fileDescriptor_a1683cf4edaf7e74) }

var fileDescriptor_a1683cf4edaf7e74 = []byte{
	// 714 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x96, 0x4f, 0x6b, 0x13, 0x4f,
	0x18, 0xc7, 0x33, 0x69, 0x7f, 0x3f, 0x70, 0x14, 0x91, 0xa9, 0x48, 0x0d, 0x65, 0x5b, 0x57, 0xb1,
	0x52, 0xda, 0x5d, 0xd3, 0xd4, 0x52, 0xad, 0x8a, 0x49, 0x69, 0x7b, 0xf1, 0x50, 0xa3, 0x27, 0x2f,
	0x32, 0x9b, 0x0c, 0xdb, 0x85, 0xcd, 0xce, 0x36, 0x33, 0x2b, 0x06, 0xf1, 0xe2, 0xcd, 0x9b, 0x20,
	0xbe, 0x00, 0xdf, 0x84, 0x57, 0xf1, 0xd6, 0x63, 0xd1, 0x8b, 0x20, 0x16, 0x49, 0x04, 0xf1, 0x5d,
	0xc8, 0xee, 0x4e, 0xfe, 0x6c, 0x32, 0x9b, 0x6c, 0x92, 0xf5, 0xb6, 0xec, 0x3c, 0xcf, 0xf7, 0x79,
	0x3e, 0xdf, 0x67, 0xf3, 0x4c, 0xe0, 0x3c, 0x76, 0x1c, 0xea, 0x39, 0x15, 0x52, 0x23, 0x0e, 0xd7,
	0x8f, 0x3c, 0x52, 0x6f, 0x68, 0x6e, 0x9d, 0x72, 0x8a, 0xae, 0x3c, 0xb4, 0x0c, 0x52, 0xe7, 0x8d,
	0xc2, 0x4d, 0xcd, 0x63, 0xd8, 0x75, 0x2b, 0x87, 0xd8, 0x72, 0xb4, 0xde, 0xf0, 0xdc, 0x82, 0x49,
	0xa9, 0x69, 0x13, 0x1d, 0xbb, 0x96, 0xee, 0x1f, 0x70, 0xcc, 0x2d, 0xea, 0xb0, 0x50, 0x20, 0xb7,
	0x52, 0xa1, 0xac, 0x46, 0x99, 0x6e, 0x60, 0x46, 0x42, 0x65, 0xfd, 0x79, 0xde, 0x20, 0x1c, 0xe7,
	0x75, 0x17, 0x9b, 0x96, 0x13, 0x04, 0x8b, 0xd8, 0x85, 0x48, 0x1b, 0x46, 0x9d, 0xe2, 0x6a, 0x05,
	0x33, 0x2e, 0x4e, 0xaf, 0x45, 0x4e, 0x19, 0x71, 0xf8, 0xb3, 0xde, 0x37, 0x22, 0x6a, 0x39, 0x12,
	0xc5, 0xad, 0x1a, 0xa1, 0x9e, 0x34, 0xf0, 0xa2, 0x49, 0x4d, 0x1a, 0x3c, 0xea, 0xfe, 0x53, 0xf8,
	0x56, 0x5d, 0x81, 0xf3, 0x8f, 0xfc, 0x26, 0xf7, 0x09, 0x2f, 0xb5, 0xeb, 0x97, 0xc9, 0x91, 0x47,
	0x18, 0x47, 0xe7, 0x61, 0xd6, 0xaa, 0xce, 0x83, 0x25, 0x70, 0x63, 0xb6, 0x9c, 0xb5, 0xaa, 0x6a,
	0x0d, 0x5e, 0x96, 0xc4, 0x32, 0x97, 0x3a, 0x8c, 0xa0, 0x03, 0x78, 0xa6, 0xf3, 0x32, 0xc8, 0x39,
	0xbb, 0xbe, 0xaa, 0x8d, 0x34, 0x53, 0xeb, 0xe4, 0x94, 0x66, 0x8f, 0x4f, 0x17, 0x33, 0xe5, 0xae,
	0x88, 0x6a, 0x88, 0xd6, 0x8a, 0xb6, 0x3d, 0xd0, 0xda, 0x1e, 0x84, 0x5d, 0x37, 0x45, 0xb9, 0xeb,
	0x5a, 0x68, 0xbd, 0xe6, 0x5b, 0xaf, 0x85, 0x43, 0x15, 0xd6, 0x6b, 0x07, 0xd8, 0x24, 0x22, 0xb7,
	0xdc, 0x93, 0xa9, 0x7e, 0x04, 0x82, 0x29, 0x5a, 0x44, 0xce, 0x34, 0x33, 0x35, 0x13, 0xda, 0x8f,
	0xf4, 0x9d, 0x0d, 0xfa, 0x5e, 0x1e, 0xd9, 0x77, 0xd8, 0x4e, 0xa4, 0xf1, 0x3c, 0x5c, 0x6c, 0xcf,
	0xe2, 0x31, 0x71, 0x78, 0xb1, 0xa7, 0x7e, 0xdc, 0xf8, 0xde, 0x00, 0xb8, 0x14, 0x9f, 0x23, 0x90,
	0x09, 0xbc, 0xd0, 0x7f, 0x26, 0xec, 0x2d, 0x24, 0x20, 0xef, 0x4f, 0x15, 0x06, 0x0c, 0x48, 0xaa,
	0x96, 0x68, 0xbf, 0x68, 0xdb, 0x71, 0xed, 0xa7, 0x35, 0xe2, 0x2f, 0x6d, 0x6c, 0x69, 0xad, 0xa1,
	0xd8, 0x33, 0x29, 0x63, 0xa7, 0x37, 0xfe, 0x0d, 0xa8, 0xb6, 0x47, 0xf9, 0x24, 0xfc, 0xc9, 0x27,
	0xf9, 0x02, 0xde, 0x03, 0x78, 0x75, 0x68, 0x9a, 0x70, 0xc3, 0x81, 0x73, 0x92, 0x63, 0x31, 0x83,
	0xcd, 0x04, 0x86, 0x48, 0xb2, 0x85, 0x27, 0x32, 0x61, 0xd5, 0x16, 0x34, 0x45, 0xdb, 0x1e, 0x42,
	0x93, 0xd6, 0x07, 0x71, 0xda, 0x76, 0x21, 0xae, 0xdc, 0x28, 0x17, 0x66, 0xfe, 0x89, 0x0b, 0xa9,
	0x7d, 0x1c, 0xeb, 0x1f, 0x20, 0xfc, 0x2f, 0x00, 0x44, 0x9f, 0x41, 0xcf, 0x06, 0x43, 0xdb, 0x09,
	0x7a, 0x8e, 0xbb, 0x0c, 0x72, 0x77, 0x27, 0x4b, 0x0e, 0xdb, 0x53, 0x6f, 0xbf, 0xfe, 0xfa, 0xeb,
	0x5d, 0xb6, 0x80, 0xf2, 0x7a, 0x47, 0x45, 0xef, 0xaa, 0xe8, 0xf2, 0x7b, 0x50, 0x7f, 0x69, 0x55,
	0x5f, 0xa1, 0x4f, 0x00, 0x9e, 0xeb, 0x08, 0x16, 0x6d, 0x3b, 0x39, 0x86, 0xe4, 0xe2, 0x48, 0x8e,
	0x21, 0xbb, 0x10, 0xd4, 0x8d, 0x00, 0x43, 0x43, 0xab, 0xe3, 0x60, 0xa0, 0x1f, 0x60, 0x70, 0xbb,
	0xa0, 0xd2, 0x18, 0x7e, 0xc6, 0xac, 0xc8, 0xdc, 0xce, 0x54, 0x1a, 0x82, 0xe9, 0x41, 0xc0, 0x74,
	0x07, 0x6d, 0x25, 0x60, 0x62, 0x7d, 0x22, 0xe1, 0x84, 0xbe, 0x03, 0x38, 0xd7, 0x2f, 0xef, 0x0f,
	0xaa, 0x34, 0x86, 0xd7, 0x53, 0x23, 0x0e, 0xd9, 0xee, 0xea, 0x76, 0x80, 0x78, 0x0b, 0x15, 0x26,
	0x40, 0x44, 0x7f, 0x80, 0x74, 0x0f, 0xa0, 0xdd, 0x31, 0xcc, 0x8f, 0xdf, 0x6a, 0xb9, 0xbd, 0x69,
	0x65, 0x04, 0xe3, 0x4e, 0xc0, 0x78, 0x0f, 0x6d, 0x27, 0x60, 0xe4, 0x83, 0x3a, 0xe1, 0x24, 0x7f,
	0x03, 0x78, 0x49, 0x52, 0xc4, 0x1f, 0xe6, 0xee, 0x18, 0x83, 0x48, 0x03, 0x77, 0xf8, 0x72, 0x56,
	0xef, 0x07, 0xb8, 0x5b, 0x68, 0x73, 0x32, 0xdc, 0xd2, 0xc1, 0x71, 0x53, 0x01, 0x27, 0x4d, 0x05,
	0xfc, 0x6c, 0x2a, 0xe0, 0x6d, 0x4b, 0xc9, 0x9c, 0xb4, 0x94, 0xcc, 0xb7, 0x96, 0x92, 0x79, 0xba,
	0x69, 0x5a, 0xfc, 0xd0, 0x33, 0xb4, 0x0a, 0xad, 0x45, 0xb4, 0xd7, 0xb0, 0xeb, 0xae, 0x85, 0xea,
	0x2f, 0xfa, 0xf4, 0x1b, 0x2e, 0x61, 0xc6, 0xff, 0xc1, 0x1f, 0xea, 0xc2, 0xdf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x4d, 0x95, 0xc2, 0xac, 0x5c, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a broadcast by id.
	Broadcast(ctx context.Context, in *QueryGetBroadcastRequest, opts ...grpc.CallOption) (*QueryGetBroadcastResponse, error)
	// Queries a list of broadcast items.
	BroadcastAll(ctx context.Context, in *QueryAllBroadcastRequest, opts ...grpc.CallOption) (*QueryAllBroadcastResponse, error)
	// Queries a sentAnnouncement by id.
	SentAnnouncement(ctx context.Context, in *QueryGetSentAnnouncementRequest, opts ...grpc.CallOption) (*QueryGetSentAnnouncementResponse, error)
	// Queries a list of sentAnnouncement items.
	SentAnnouncementAll(ctx context.Context, in *QueryAllSentAnnouncementRequest, opts ...grpc.CallOption) (*QueryAllSentAnnouncementResponse, error)
	// Queries a timeoutAnnouncement by id.
	TimeoutAnnouncement(ctx context.Context, in *QueryGetTimeoutAnnouncementRequest, opts ...grpc.CallOption) (*QueryGetTimeoutAnnouncementResponse, error)
	// Queries a list of timeoutAnnouncement items.
	TimeoutAnnouncementAll(ctx context.Context, in *QueryAllTimeoutAnnouncementRequest, opts ...grpc.CallOption) (*QueryAllTimeoutAnnouncementResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Broadcast(ctx context.Context, in *QueryGetBroadcastRequest, opts ...grpc.CallOption) (*QueryGetBroadcastResponse, error) {
	out := new(QueryGetBroadcastResponse)
	err := c.cc.Invoke(ctx, "/Liberty30.usappchain.announcement.Query/Broadcast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BroadcastAll(ctx context.Context, in *QueryAllBroadcastRequest, opts ...grpc.CallOption) (*QueryAllBroadcastResponse, error) {
	out := new(QueryAllBroadcastResponse)
	err := c.cc.Invoke(ctx, "/Liberty30.usappchain.announcement.Query/BroadcastAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SentAnnouncement(ctx context.Context, in *QueryGetSentAnnouncementRequest, opts ...grpc.CallOption) (*QueryGetSentAnnouncementResponse, error) {
	out := new(QueryGetSentAnnouncementResponse)
	err := c.cc.Invoke(ctx, "/Liberty30.usappchain.announcement.Query/SentAnnouncement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SentAnnouncementAll(ctx context.Context, in *QueryAllSentAnnouncementRequest, opts ...grpc.CallOption) (*QueryAllSentAnnouncementResponse, error) {
	out := new(QueryAllSentAnnouncementResponse)
	err := c.cc.Invoke(ctx, "/Liberty30.usappchain.announcement.Query/SentAnnouncementAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TimeoutAnnouncement(ctx context.Context, in *QueryGetTimeoutAnnouncementRequest, opts ...grpc.CallOption) (*QueryGetTimeoutAnnouncementResponse, error) {
	out := new(QueryGetTimeoutAnnouncementResponse)
	err := c.cc.Invoke(ctx, "/Liberty30.usappchain.announcement.Query/TimeoutAnnouncement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TimeoutAnnouncementAll(ctx context.Context, in *QueryAllTimeoutAnnouncementRequest, opts ...grpc.CallOption) (*QueryAllTimeoutAnnouncementResponse, error) {
	out := new(QueryAllTimeoutAnnouncementResponse)
	err := c.cc.Invoke(ctx, "/Liberty30.usappchain.announcement.Query/TimeoutAnnouncementAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a broadcast by id.
	Broadcast(context.Context, *QueryGetBroadcastRequest) (*QueryGetBroadcastResponse, error)
	// Queries a list of broadcast items.
	BroadcastAll(context.Context, *QueryAllBroadcastRequest) (*QueryAllBroadcastResponse, error)
	// Queries a sentAnnouncement by id.
	SentAnnouncement(context.Context, *QueryGetSentAnnouncementRequest) (*QueryGetSentAnnouncementResponse, error)
	// Queries a list of sentAnnouncement items.
	SentAnnouncementAll(context.Context, *QueryAllSentAnnouncementRequest) (*QueryAllSentAnnouncementResponse, error)
	// Queries a timeoutAnnouncement by id.
	TimeoutAnnouncement(context.Context, *QueryGetTimeoutAnnouncementRequest) (*QueryGetTimeoutAnnouncementResponse, error)
	// Queries a list of timeoutAnnouncement items.
	TimeoutAnnouncementAll(context.Context, *QueryAllTimeoutAnnouncementRequest) (*QueryAllTimeoutAnnouncementResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Broadcast(ctx context.Context, req *QueryGetBroadcastRequest) (*QueryGetBroadcastResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Broadcast not implemented")
}
func (*UnimplementedQueryServer) BroadcastAll(ctx context.Context, req *QueryAllBroadcastRequest) (*QueryAllBroadcastResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastAll not implemented")
}
func (*UnimplementedQueryServer) SentAnnouncement(ctx context.Context, req *QueryGetSentAnnouncementRequest) (*QueryGetSentAnnouncementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SentAnnouncement not implemented")
}
func (*UnimplementedQueryServer) SentAnnouncementAll(ctx context.Context, req *QueryAllSentAnnouncementRequest) (*QueryAllSentAnnouncementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SentAnnouncementAll not implemented")
}
func (*UnimplementedQueryServer) TimeoutAnnouncement(ctx context.Context, req *QueryGetTimeoutAnnouncementRequest) (*QueryGetTimeoutAnnouncementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TimeoutAnnouncement not implemented")
}
func (*UnimplementedQueryServer) TimeoutAnnouncementAll(ctx context.Context, req *QueryAllTimeoutAnnouncementRequest) (*QueryAllTimeoutAnnouncementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TimeoutAnnouncementAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Broadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetBroadcastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Broadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Liberty30.usappchain.announcement.Query/Broadcast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Broadcast(ctx, req.(*QueryGetBroadcastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BroadcastAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllBroadcastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BroadcastAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Liberty30.usappchain.announcement.Query/BroadcastAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BroadcastAll(ctx, req.(*QueryAllBroadcastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SentAnnouncement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetSentAnnouncementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SentAnnouncement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Liberty30.usappchain.announcement.Query/SentAnnouncement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SentAnnouncement(ctx, req.(*QueryGetSentAnnouncementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SentAnnouncementAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllSentAnnouncementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SentAnnouncementAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Liberty30.usappchain.announcement.Query/SentAnnouncementAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SentAnnouncementAll(ctx, req.(*QueryAllSentAnnouncementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TimeoutAnnouncement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetTimeoutAnnouncementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TimeoutAnnouncement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Liberty30.usappchain.announcement.Query/TimeoutAnnouncement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TimeoutAnnouncement(ctx, req.(*QueryGetTimeoutAnnouncementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TimeoutAnnouncementAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllTimeoutAnnouncementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TimeoutAnnouncementAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Liberty30.usappchain.announcement.Query/TimeoutAnnouncementAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TimeoutAnnouncementAll(ctx, req.(*QueryAllTimeoutAnnouncementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Liberty30.usappchain.announcement.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Broadcast",
			Handler:    _Query_Broadcast_Handler,
		},
		{
			MethodName: "BroadcastAll",
			Handler:    _Query_BroadcastAll_Handler,
		},
		{
			MethodName: "SentAnnouncement",
			Handler:    _Query_SentAnnouncement_Handler,
		},
		{
			MethodName: "SentAnnouncementAll",
			Handler:    _Query_SentAnnouncementAll_Handler,
		},
		{
			MethodName: "TimeoutAnnouncement",
			Handler:    _Query_TimeoutAnnouncement_Handler,
		},
		{
			MethodName: "TimeoutAnnouncementAll",
			Handler:    _Query_TimeoutAnnouncementAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "announcement/query.proto",
}

func (m *QueryGetBroadcastRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetBroadcastRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetBroadcastRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetBroadcastResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetBroadcastResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetBroadcastResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Broadcast.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllBroadcastRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllBroadcastRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllBroadcastRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllBroadcastResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllBroadcastResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllBroadcastResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Broadcast) > 0 {
		for iNdEx := len(m.Broadcast) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Broadcast[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetSentAnnouncementRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSentAnnouncementRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSentAnnouncementRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetSentAnnouncementResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSentAnnouncementResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSentAnnouncementResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.SentAnnouncement.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllSentAnnouncementRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllSentAnnouncementRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllSentAnnouncementRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllSentAnnouncementResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllSentAnnouncementResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllSentAnnouncementResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.SentAnnouncement) > 0 {
		for iNdEx := len(m.SentAnnouncement) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SentAnnouncement[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetTimeoutAnnouncementRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetTimeoutAnnouncementRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetTimeoutAnnouncementRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetTimeoutAnnouncementResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetTimeoutAnnouncementResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetTimeoutAnnouncementResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.TimeoutAnnouncement.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllTimeoutAnnouncementRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllTimeoutAnnouncementRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllTimeoutAnnouncementRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllTimeoutAnnouncementResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllTimeoutAnnouncementResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllTimeoutAnnouncementResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.TimeoutAnnouncement) > 0 {
		for iNdEx := len(m.TimeoutAnnouncement) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TimeoutAnnouncement[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetBroadcastRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetBroadcastResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Broadcast.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllBroadcastRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllBroadcastResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Broadcast) > 0 {
		for _, e := range m.Broadcast {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetSentAnnouncementRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetSentAnnouncementResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.SentAnnouncement.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllSentAnnouncementRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllSentAnnouncementResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.SentAnnouncement) > 0 {
		for _, e := range m.SentAnnouncement {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetTimeoutAnnouncementRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetTimeoutAnnouncementResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TimeoutAnnouncement.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllTimeoutAnnouncementRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllTimeoutAnnouncementResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.TimeoutAnnouncement) > 0 {
		for _, e := range m.TimeoutAnnouncement {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetBroadcastRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetBroadcastRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetBroadcastRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetBroadcastResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetBroadcastResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetBroadcastResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Broadcast", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Broadcast.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllBroadcastRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllBroadcastRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllBroadcastRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllBroadcastResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllBroadcastResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllBroadcastResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Broadcast", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Broadcast = append(m.Broadcast, Broadcast{})
			if err := m.Broadcast[len(m.Broadcast)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSentAnnouncementRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSentAnnouncementRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSentAnnouncementRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSentAnnouncementResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSentAnnouncementResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSentAnnouncementResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SentAnnouncement", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SentAnnouncement.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllSentAnnouncementRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllSentAnnouncementRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllSentAnnouncementRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllSentAnnouncementResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllSentAnnouncementResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllSentAnnouncementResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SentAnnouncement", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SentAnnouncement = append(m.SentAnnouncement, SentAnnouncement{})
			if err := m.SentAnnouncement[len(m.SentAnnouncement)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetTimeoutAnnouncementRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetTimeoutAnnouncementRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetTimeoutAnnouncementRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetTimeoutAnnouncementResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetTimeoutAnnouncementResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetTimeoutAnnouncementResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutAnnouncement", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TimeoutAnnouncement.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllTimeoutAnnouncementRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllTimeoutAnnouncementRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllTimeoutAnnouncementRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllTimeoutAnnouncementResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllTimeoutAnnouncementResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllTimeoutAnnouncementResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutAnnouncement", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TimeoutAnnouncement = append(m.TimeoutAnnouncement, TimeoutAnnouncement{})
			if err := m.TimeoutAnnouncement[len(m.TimeoutAnnouncement)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
